changing from checksum_scripts to BFI_scripts

diff --git a/.github/workflows/github_workflow_process.yaml b/.github/workflows/github_workflow_process.yaml
--- a/.github/workflows/github_workflow_process.yaml
+++ b/.github/workflows/github_workflow_process.yaml
@@ -81,11 +81,11 @@ jobs:
         id: check-pr
         if: github.event_name == 'push' && github.ref != 'refs/heads/main'
         run: |
-            echo "Checking for PR in datadigipres/checksum_scripts for branch: $BRANCH_NAME"
+            echo "Checking for PR in bfidatadigipres/BFI_scripts for branch: $BRANCH_NAME"
 
             # Query the GitHub API to check for existing PRs
             PR_EXISTS=$(gh pr list \
-                --repo "bfidatadigipres/checksum_scripts" \
+                --repo "bfidatadigipres/BFI_scripts \
                 --head "${BRANCH_NAME}" \
                 --base main \
                 --state open \
@@ -113,7 +113,7 @@ jobs:
         run: |
               echo "Creating PR for branch $REF_NAME"
               gh pr create \
-                --repo "bfidatadigipres/checksum_scripts" \
+                --repo "bfidatadigipres/BFI_scripts" \
                 --base main \
                 --head "$REPO_OWNER:$REF_NAME" \
                 --title "Automated PR for branch: $REF_NAME" \
@@ -182,7 +182,7 @@ jobs:
           run: |
             echo "Checking for PR on branch: $BRANCH_NAME"
 
-            PR_NUMBER=$(gh pr list --repo "bfidatadigipres/checksum_scripts" --head "$BRANCH_NAME" --state open --json number --jq '.[0].number' 2>/dev/null || echo "error")
+            PR_NUMBER=$(gh pr list --repo "bfidatadigipres/BFI_scripts" --head "$BRANCH_NAME" --state open --json number --jq '.[0].number' 2>/dev/null || echo "error")
 
             echo "Found PR number: $PR_NUMBER"
             if [  "$PR_NUMBER" != "error" ]; then
@@ -198,7 +198,7 @@ jobs:
           with:
             issue-number: ${{ steps.check-pr.outputs.number }}
             edit-mode: replace
-            repository: bfidatadigipres/checksum_scripts
+            repository: bfidatadigipres/BFI_scripts
             body: |
               **Automated Pylint Report** 🧑‍💻
 
